pipeline {
    agent {label 'ec2-fleet'}
    environment {
        def BUILDVERSION = sh(script: "echo `date +%s`", returnStdout: true).trim()
    }
    stages {
        //stage('Clone Repository') {
        // steps {
        //       script {
        //      def credentialsId = 'jenkins-nitin'
        //      def repoUrl = 'https://github.com/nitinverma9/python-app'
        //      checkout([$class: 'GitSCM',
        //           branches: [[name: 'main']],
        //           userRemoteConfigs: [[credentialsId: credentialsId, url: repoUrl]]])
        //      }
        //   }
        // }
        
        stage('Build') {
             steps {
                    script {
                       sh """
                          sudo -u ec2-user docker build -t python-app:${BUILDVERSION} -f deploy/Dockerfile .
                          """ 
                    }        
                }            
    }
}
}
